### ISSUE TITLE
fix size of forward and back arrows

### ISSUE THREAD

**Issue by blros** [blros/urarina-wax#9]
make them the same size

**Comment by emkow2020** [comment]
The arrows show up on my Windows computer correctly, on Allen's Mac the back arrow is considerably smaller. 
The issue has not been solved yet.

**Comment by blros** [comment]
Using Chrome and Safari on my Mac, the back arrow is still small, but when I use Firefox, both arrows displayed correctly at the same size. I tried clearing my cache is those browsers, and I looked at all the css files---don't know why this issue persists.

**Comment by blros** [comment]
I think I fixed it by just using the right-pointer and flipping it 180 degrees with the following line in _layouts/generic_collection_item_tab.html

`<div style="transform: rotateY(180deg);" class='pagination-link' id='prevlink'><a href='{{ prevlink | absolute_url }}' >&#9658;</a></div>`

It's a bit of a hack, but from what I'm reading different browsers handle these characters inconsistently. When I copied and pasted the text from the webpage to MS Word or SublimeText, they displayed correctly. So I just used the right pointer twice, but the first time flipped it 180 degrees.

**Comment by emkow2020** [comment]
These two &#9664;   &#9654;  (black triangles #9664,   #9654) 
   work a little better than &#9668;   &#9658;  (black pointers #9668,   #9658). 

The rotateY trick is a little better, but still not exactly the same size.

Using an image ( i.e. img src=left_arrow_page.png makes them both the same size, but doesn't have the fancy "hover" decoration.

**Comment by emkow2020** [comment]
Minor change to use &#9664 as the left, and rotate it for the right arrow.
  This looks the same size on mac ... today.
